spring:
  datasource:
    url: &dbURL jdbc:mysql://localhost:3306/myDB
    username: &dbUser
    password: &dbPassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
